import '@/app/globals.css'

import type { Metadata } from 'next'
import { Montserrat, Open_Sans as OpenSans } from 'next/font/google'
import { notFound } from 'next/navigation'
import { hasLocale, NextIntlClientProvider } from 'next-intl'

import { ThemeProvider } from '@/contexts/theme'
import { routing } from '@/i18n/routing'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const openSans = OpenSans({
  subsets: ['latin'],
  variable: '--font-open-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale?: string }>
}>) {
  const paramsValue = await params
  const locale = paramsValue?.locale

  if (!locale || !hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html suppressHydrationWarning lang={locale} className="h-full">
      <head />

      <body
        className={`h-full min-h-screen ${montserrat.variable} ${openSans.variable}`}
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}

            <div className="texture-overlay" aria-hidden="true" />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
