import '@/app/globals.css'

import type { Metadata } from 'next'
import {
  Libertinus_Math as LibertinusMath,
  Montserrat,
  Rubik,
} from 'next/font/google'
import { notFound } from 'next/navigation'
import { hasLocale, NextIntlClientProvider } from 'next-intl'

import { ThemeProvider } from '@/contexts/theme'
import { routing } from '@/i18n/routing'

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const libertinusMath = LibertinusMath({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-libertinus-math',
  display: 'swap',
  fallback: ['var(--font-montserrat)', 'sans-serif'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale?: string }>
}>) {
  const paramsValue = await params
  const locale = paramsValue?.locale

  if (!locale || !hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html suppressHydrationWarning lang={locale} className="h-full">
      <head />

      <body
        className={`min-h-screen ${rubik.variable} ${montserrat.variable} ${libertinusMath.variable}`}
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
